image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3001
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: ignore
tasks:
  - before: nvm install 16
  - init: npm install
  - command: >
      cat .env.example >> .env &&
      echo BACKEND_URL=$(gp url 3001) >> .env && 
      npm run start
    openMode: split-right

vscode:
  extensions:
    - esbenp.prettier-vscode
